_target_: src.models.mre_brain_module.MREBrainLitModule

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.001
  weight_decay: 0.0
  momentum: 0.9
  nesterov: true

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  _partial_: true
  T_0: 10
  eta_min: 0.000001

net:
  _target_: src.models.components.resnet3d.ResNet3D
  num_input_maps:  1
  block_name:  "PreActResNetBlock"
  num_blocks: [3,4,6,4,3]
  c_hidden : [8,16,32,64,128]
  cat_input_type: "sex_study"
  arc_type: "1"
  